### ISSUE TITLE
Feature request: display timer in toolbar if it is running, rather than temperature

### ISSUE THREAD

**Issue by lindseyhanna-wf** [matthewnitschke/ember-macos#41]
Without having the app open there's no way to know if a timer is running since only temperature is displayed. It'd be nice to have the option to display remaining time up there when a timer is going.

<img width="78" alt="image" src="https://github.com/matthewnitschke/EmberMate/assets/2278667/a6110260-ab1d-4364-835f-f2c19c50e44f">

**Comment by matthewnitschke** [comment]
I had spiked the idea of including the time left in the menu bar but opted to not include it since the text rendered is not monospaced and each second glitched the icon back and forth

2 potential options would be:
- Just render the minutes left: `3min` -> `2min` -> `1min` -> `>1min`
- Just update the icon to a clock when the timer is running

Latter would be very easy, former would provide additional context

I'll spend a bit of time investigating both, thanks for the idea!
